<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mostafa Student System</title>

    <link rel="stylesheet" href="style.css">
</head>

<body>

    <h1>Mostafa Student System</h1>

    <p>مرحباً بك في نظام إدارة الطلاب</p>

    <button onclick="addStudent()">إضافة طالب</button>
    <button onclick="showStudents()">عرض الطلاب</button>

    <div id="studentsList"></div>

    <script src="script.js"></script>

</body>
</html>
